In [1]:
import pandas as pd
import numpy as np

In [94]:
data1 = pd.read_csv('fifa19_data.csv')

data1.head()

   Unnamed: 0      ID  ... GKReflexes  Release Clause
0           0  158023  ...        8.0         €226.5M
1           1   20801  ...       11.0         €127.1M
2           2  190871  ...       11.0         €228.1M
3           3  193080  ...       94.0         €138.6M
4           4  192985  ...       13.0         €196.4M

[5 rows x 89 columns]

In [0]:
x_features = data1[['Age','Potential','Wage','BallControl','SprintSpeed','Agility','GKHandling']]
y = data1['Release Clause']

In [134]:
x_features.isnull().any()

Age            False
Potential      False
Wage           False
BallControl     True
SprintSpeed     True
Agility         True
GKHandling      True
dtype: bool

In [135]:
for x in x_features:
  print(type(x))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [137]:
data1['Wage']=data1['Wage'].str.replace("€",'')
data1['Wage']=data1['Wage'].str.replace("M",'')
data1['Wage']

0        nan
1        nan
2        nan
3        nan
4        nan
5        nan
6        nan
7        nan
8        nan
9        nan
10       nan
11       nan
12       nan
13       nan
14       nan
15       nan
16       nan
17       nan
18       nan
19       nan
20       nan
21       nan
22       nan
23       nan
24       nan
25       nan
26       nan
27       nan
28       nan
29       nan
        ...
18177     1K
18178     1K
18179     1K
18180     1K
18181     1K
18182     1K
18183     1K
18184     1K
18185     1K
18186     1K
18187     1K
18188     1K
18189     1K
18190     1K
18191     1K
18192     1K
18193     1K
18194     1K
18195     1K
18196     1K
18197     1K
18198     1K
18199     1K
18200     1K
18201     1K
18202     1K
18203     1K
18204     1K
18205     1K
18206     1K
Name: Wage, Length: 18207, dtype: object

In [125]:
for test in data1['Wage']:
  if 'M' in test:
    print('MILLION')

TypeError: ignored

In [123]:
for number in enumerate(data1['Wage'].astype('str')):
  if number[1].find('K') != -1:
    x= number[1].replace("K", '')
    data1['Wage'][number[0]] = float(x)/1000
print(data1['Wage'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

KeyboardInterrupt: ignored

In [97]:
x_features['GKHandling'].fillna(np.mean(x_features['GKHandling']),inplace=True)
x_features['SprintSpeed'].fillna(np.mean(x_features['GKHandling']),inplace=True)
x_features['Agility'].fillna(np.mean(x_features['GKHandling']),inplace=True)
x_features['GKHandling'].fillna(np.mean(x_features['GKHandling']),inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [98]:
x_features.describe()

                Age     Potential  ...       Agility    GKHandling
count  18207.000000  18207.000000  ...  18207.000000  18207.000000
mean      25.122206     71.307299  ...     63.379403     16.391596
std        4.669943      6.136496  ...     14.943150     16.884598
min       16.000000     48.000000  ...     14.000000      1.000000
25%       21.000000     67.000000  ...     55.000000      8.000000
50%       25.000000     71.000000  ...     66.000000     11.000000
75%       28.000000     75.000000  ...     74.000000     14.000000
max       45.000000     95.000000  ...     96.000000     92.000000

[8 rows x 6 columns]

In [0]:
y=y.str.replace("€",'')
y=y.str.replace("M",'')
print(y)

In [106]:
for number in enumerate(y.astype('str')):
    if number[1].find('K') != -1:
        x= number[1].replace("K", '')
        y[number[0]] = float(x)/1000
print(y)

0        226.5
1        127.1
2        228.1
3        138.6
4        196.4
5        172.1
6        137.4
7          164
8        104.6
9        144.5
10       127.1
11       156.8
12        90.2
13         111
14       121.3
15       153.5
16       160.7
17       165.8
18       123.3
19       113.7
20       105.6
21         111
22        62.7
23       119.3
24        44.6
25       166.1
26       137.3
27       126.4
28         NaN
29       105.4
         ...
18177    0.193
18178    0.094
18179    0.119
18180    0.078
18181    0.109
18182    0.101
18183      NaN
18184    0.078
18185    0.088
18186    0.167
18187    0.066
18188    0.143
18189    0.125
18190    0.165
18191    0.119
18192    0.119
18193    0.099
18194    0.109
18195    0.153
18196    0.113
18197    0.088
18198    0.165
18199    0.175
18200    0.143
18201    0.153
18202    0.143
18203    0.113
18204    0.165
18205    0.143
18206    0.165
Name: Release Clause, Length: 18207, dtype: object

In [110]:
y=y.astype('float')
y.describe()

y.fillna(np.mean(y),inplace=True)
y

0        226.500000
1        127.100000
2        228.100000
3        138.600000
4        196.400000
5        172.100000
6        137.400000
7        164.000000
8        104.600000
9        144.500000
10       127.100000
11       156.800000
12        90.200000
13       111.000000
14       121.300000
15       153.500000
16       160.700000
17       165.800000
18       123.300000
19       113.700000
20       105.600000
21       111.000000
22        62.700000
23       119.300000
24        44.600000
25       166.100000
26       137.300000
27       126.400000
28         4.585061
29       105.400000
            ...
18177      0.193000
18178      0.094000
18179      0.119000
18180      0.078000
18181      0.109000
18182      0.101000
18183      4.585061
18184      0.078000
18185      0.088000
18186      0.167000
18187      0.066000
18188      0.143000
18189      0.125000
18190      0.165000
18191      0.119000
18192      0.119000
18193      0.099000
18194      0.109000
18195      0.153000
18196      0.113000
18197      0.088000
18198      0.165000
18199      0.175000
18200      0.143000
18201      0.153000
18202      0.143000
18203      0.113000
18204      0.165000
18205      0.143000
18206      0.165000
Name: Release Clause, Length: 18207, dtype: float64

In [0]:
y = data1['Release Clause']
y_fixed = []

y = y.astype(str)

for number in y:
  for digit in range(len(number)):
      new_number = ''
      
      if number[digit]!='€':
        new_number += number[digit]
        
  if new_number[-1]=='M':
    newnew_number = ''
    for newdigit in new_number:
      if newdigit!='M':
        newnew_number+=newdigit
    print(newnew_number)
    #new_number = float(newnew_number)*1000000

  elif new_number[-1]!='K':
    newnew_number = ''
    for newdigit in new_number:
      if newdigit!='K':
        newnew_number+=newdigit
    print(newnew_number)
    #new_number = float(newnew_number)*1000

  y_fixed.append(new_number)
  print(new_number)
      
print(y)
      
      #if number[digit]==('€'):
        #number.replace('€','')
        #print(number)

In [0]:
y = data1['Release Clause']
temp_wordlist = []

for word in y:
  #the element
  print('\n\n',word)
  
  #Store each letter in the word
  letters = []
  
  for x in range(len(word)):
    if word[x]==('€'):
      letters.append(word[x])
    
  new_word = ''
  for y in letters:
    new_word += str(y)
  
  #Convert to millions
  
  new_word = (float(new_word))*1000000
  
  temp_wordlist.append(new_word)
  
  letters.clear()
  print(new_word)

temp_wordlist
#y.clear()
#y.append(temp_wordlist)

In [0]:
import sklearn.model_selection as ms
from sklearn.tree import DecisionTreeClassifier as dtc

In [0]:
x_train, x_test, y_train, y_test = ms.train_test_split(x_features,y,test_size=0.3)

In [113]:
model_a = dtc(criterion='entropy')
model_b = dtc(criterion='gini')

model_a.fit(x_train,y_train)
model_b.fit(x_train,y_train)

ValueError: ignored

In [0]:
y

In [0]:
y = data1['Release Clause']

In [2]:
strr = 'sdsds'
strr[-1]

's'